-- MySQL Script generated by MySQL Workbench
-- Thu May  9 22:25:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kanbanIT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kanbanIT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kanbanIT` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kanbanIT` ;

-- -----------------------------------------------------
-- Table `kanbanIT`.`statustasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanbanIT`.`statustasks` (
  `statusId` INT NOT NULL AUTO_INCREMENT,
  `statusname` VARCHAR(50) NOT NULL DEFAULT 'NO_STATUS',
  `statusdescription` VARCHAR(200) NULL,
   `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `statusname_UNIQUE` (`statusname` ASC) VISIBLE,
  PRIMARY KEY (`statusId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `kanbanIT`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanbanIT`.`tasks` (
  `taskId` INT NOT NULL AUTO_INCREMENT,
  `taskTitle` TEXT(100) NOT NULL,
  `taskDescription` TEXT(500) NULL DEFAULT NULL,
  `taskAssignees` TEXT(30) NULL DEFAULT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `statusId` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`taskId`),
  UNIQUE INDEX `taskId_UNIQUE` (`taskId` ASC) VISIBLE,
  INDEX `fk_tasks_statustasks_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_statustasks`
    FOREIGN KEY (`statusId`)
    REFERENCES `kanbanIT`.`statustasks` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `kanbanIT`.`statustasks` (statusid, statusname, statusdescription) VALUES
(1, 'No Status', 'The default status'),
(2, 'To Do', NULL),
(3, 'Doing', 'Being worked on'),
(4, 'Done', 'Finished');

COMMIT;

INSERT INTO `kanbanIT`.`tasks` (`taskTitle`, `taskDescription`, `taskAssignees`, `createdOn`, `updatedOn`, `statusId`) VALUES ('TaskTitle1TaskTitle2TaskTitle3TaskTitle4TaskTitle5TaskTitle6TaskTitle7TaskTitle8TaskTitle9TaskTitle0', 'Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti1Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti2Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti3Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti4Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti5', 'Assignees1Assignees2Assignees3', '2024-04-22 09:00:00', '2024-04-22 09:00:00', '1');
INSERT INTO `kanbanIT`.`tasks` (`taskTitle`, `createdOn`, `updatedOn`, `statusId`) VALUES ('Repository', '2024-04-22 09:05:00', '2024-04-22 14:00:00', '2');
INSERT INTO `kanbanIT`.`tasks` (`taskTitle`, `taskDescription`, `taskAssignees`, `createdOn`, `updatedOn`, `statusId`) VALUES ('ดาต้าเบส', 'ສ້າງຖານຂໍ້ມູນ', 'あなた、彼、彼女 (私ではありません)', '2024-04-22 09:10:00', '2024-04-25 00:00:00', '3');
INSERT INTO `kanbanIT`.`tasks` (`taskTitle`, `taskDescription`, `taskAssignees`, `createdOn`, `updatedOn`, `statusId`) VALUES ('_Infrastructure_', '_Setup containers_', 'ไก่งวง กับ เพนกวิน', '2024-04-22 09:15:00', '2024-04-22 10:00:00', '4');
-- INSERT INTO `kanbanIT`.`tasks` (`taskId`, `taskTitle`, `createdOn`, `updatedOn`, `statusId`) VALUES ('5', 'DevSecOps', '2024-05-08 22:39:00', '2024-05-08 22:39:00', '1');
-- INSERT INTO `kanbanIT`.`tasks` (`taskId`, `taskTitle`, `taskDescription`, `taskAssignees`, `createdOn`, `updatedOn`, `statusId`) VALUES ('6', 'DevSecOps1DevSecOps2DevSecOps3DevSecOps4DevSecOps5DevSecOps6DevSecOps7DevSecOps8DevSecOps9DevSecOps0', 'Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti1Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti2Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti3Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti4Descripti1Descripti2Descripti3Descripti4Descripti5Descripti6Descripti7Descripti8Descripti9Descripti5', 'Assignees1Assignees2Assignees3', '2024-05-08 22:38:00', '2024-05-08 22:39:00', '2');

COMMIT;

