CREATE DATABASE `SJ-3`;
CREATE TABLE IF NOT EXISTS `SJ-3`.`TASKS` (
  `taskId` INT NOT NULL AUTO_INCREMENT,
  `taskTitle` TEXT(100) NOT NULL,
  `taskDescription` TEXT(500) NULL DEFAULT NULL,
  `taskAssignees` TEXT(30) NULL DEFAULT NULL,
  `taskStatus` ENUM('NO_STATUS', 'TO_DO', 'DOING', 'DONE') NOT NULL DEFAULT 'NO_STATUS',
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`taskId`),
  UNIQUE INDEX `taskId_UNIQUE` (`taskId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


select * from TASKS;