-- MySQL Script generated by MySQL Workbench
-- Wed May  8 22:11:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kanbanIT
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kanbanIT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kanbanIT` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kanbanIT` ;
-- -----------------------------------------------------
-- Table `kanbanIT`.`statustasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanbanIT`.`statustasks` (
  `statusid` INT NOT NULL AUTO_INCREMENT,
  `statusname` VARCHAR(50) NOT NULL,
  `statusdescription` VARCHAR(200) NULL,
  UNIQUE INDEX `statusname_UNIQUE` (`statusname` ASC) VISIBLE,
  PRIMARY KEY (`statusid`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `kanbanIT`.`TASKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanbanIT`.`TASKS` (
  `taskId` INT NOT NULL AUTO_INCREMENT,
  `taskTitle` TEXT(100) NOT NULL,
  `taskDescription` TEXT(500) NULL DEFAULT NULL,
  `taskAssignees` TEXT(30) NULL DEFAULT NULL,
  `taskStatus` ENUM('NO_STATUS', 'TO_DO', 'DOING', 'DONE') NOT NULL DEFAULT 'NO_STATUS',
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `statustasks_statusid` INT NOT NULL,
  PRIMARY KEY (`taskId`),
  UNIQUE INDEX `taskId_UNIQUE` (`taskId` ASC) VISIBLE,
  INDEX `fk_TASKS_statustasks_idx` (`statustasks_statusid` ASC) VISIBLE,
  CONSTRAINT `fk_TASKS_statustasks`
    FOREIGN KEY (`statustasks_statusid`)
    REFERENCES `kanbanIT`.`statustasks` (`statusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
-- AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
